# Generated by Django 4.0 on 2022-02-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_alter_invoice_status_alter_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(blank=True, choices=[('Paris', 'Paris'), ('Seine-et-Marne', 'Seine-et-Marne'), ('Yvelines', 'Yvelines'), ('Essonne ', 'Essonne '), ('Hauts-de-Seine', 'Hauts-de-Seine'), ('Seine-Saint-Denis', 'Seine-Saint-Denis'), ('Val-de-Marne', 'Val-de-Marne'), ("Val-d'Oise", "Val-d'Oise")], max_length=100),
        ),
    ]
